import NavBar from "@/components/NavBar";
import "./globals.css";   
import styles from './page.module.css'
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <div className="min-h-screen flex justify-between flex-col max-w-[1336px] ">
          <NavBar/>
          {children}
          <Footer/>
          </div>
      </body>
    </html>
  );
}
