import NavBar from "@/components/NavBar/page";
import "./globals.css";
import Footer from "@/components/Footer/page";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
        <div  className="container">
        <NavBar/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
