import NavBar from "@/components/NavBar/page";
import "./globals.css";
import Footer from "@/components/Footer/page";
import { ThemeProvider } from "@/context/ThemeContext";
// import { ThemeContext } from "@/context/ThemeContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
        <ThemeProvider>
        <div  className="container">
        <NavBar/>
        {children}
        <Footer/>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
